name: WE are IF
favicon: null
layout_spectrum: 1
typography_spectrum: 0.95833
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f1ec'
    - '#373737'
    - '#ccc5bd'
    - '#595856'
    - '#837e78'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.7373177534900606
  rhythmicContrast: 0.75
purpose: []
